# ==========================
# BASE DE DATOS (DOCKER)
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.open-in-view=false

# ==========================
# SWAGGER OFF
# ==========================
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

# ==========================
# JWT
# ==========================
security.jwt.issuer=mobilesco
security.jwt.access-ttl-minutes=15
security.jwt.refresh-ttl-days=30
security.jwt.secret-base64=${JWT_SECRET_BASE64}

# ==========================
# UPLOADS
# ==========================
app.uploads.dir=${UPLOAD_DIR:/app/uploads}

# MULTIPART
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

server.address=0.0.0.0
